// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAepqvywnyrHvPZQrNWZvs9WrdGeWqpgmA',
    appId: '1:778523140147:web:df81635eadec3b654ac346',
    messagingSenderId: '778523140147',
    projectId: 'makenairtel',
    authDomain: 'makenairtel.firebaseapp.com',
    storageBucket: 'makenairtel.appspot.com',
    measurementId: 'G-BE220KW0RC',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAesfBUHU6Jy_INKuCn8OJROI7V2pBDFtw',
    appId: '1:778523140147:ios:32bf86654d068c464ac346',
    messagingSenderId: '778523140147',
    projectId: 'makenairtel',
    storageBucket: 'makenairtel.appspot.com',
    iosBundleId: 'com.example.makenairtel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAesfBUHU6Jy_INKuCn8OJROI7V2pBDFtw',
    appId: '1:778523140147:ios:0b9434b92085d56c4ac346',
    messagingSenderId: '778523140147',
    projectId: 'makenairtel',
    storageBucket: 'makenairtel.appspot.com',
    iosBundleId: 'com.example.makenairtel.RunnerTests',
  );
}
